plugins {
	id 'fabric-loom' version '1.13-SNAPSHOT'
	id 'maven-publish'
}

version = "${project.mod_version}-mc${project.minecraft_version}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		name = 'TerraformersMC'
		url = 'https://maven.terraformersmc.com/'
	}
	maven {
		name = 'G4me4u Maven'
		url = 'https://maven.g4mesoft.com/releases'
	}
}

// See https://github.com/TerraformersMC/GradleScripts/blob/2.5/ferry.gradle

ext.includeMod = { Object dep ->
    dependencies.modImplementation dep
    dependencies.include dep
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modCompileOnly "net.fabricmc:fabric-loader:${project.loader_version}"
	// Include G4mespeed UI
	includeMod "com.g4mesoft.ui:g4mespeed-ui:${project.g4mespeed_ui_version}-mc${project.minecraft_version}"
	// ModMenu integration
	modCompileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
	// ModMenu requires some fabric api modules
	modCompileOnly(fabricApi.module("fabric-screen-api-v1", project.fabric_version))
	modCompileOnly(fabricApi.module("fabric-key-binding-api-v1", project.fabric_version))
	modCompileOnly(fabricApi.module("fabric-lifecycle-events-v1", project.fabric_version))
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.mod_version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	setupRepositories(repositories)
}

void setupRepositories(RepositoryHandler repositories) {
	//repositories.mavenLocal() // uncomment for testing
	def ENV = System.getenv()
	if (ENV.MAVEN_URL && ENV.MAVEN_ALIAS && ENV.MAVEN_TOKEN) {
		repositories.maven {
			url "${ENV.MAVEN_URL}/releases"
			credentials {
				username ENV.MAVEN_ALIAS
				password ENV.MAVEN_TOKEN
			}
			authentication {
				basic(BasicAuthentication)
			}
		}
	} else {
		throw GradleException("No Maven credentials specified")
	}
}
